/***********************************************************************/
/*                                                                     */
/*  FILE        :rimokonn.c                                            */
/*  DATE        :Thu, Sep 15, 2022                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3694F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  

#include "lcd.h"
#include "iodefine.h"
#include "led.h"
#include "intsw.h"
#include "timerA.h"

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	InitLED();
	initSWint();
    InitLcd();
	iniTimerA();

	while(1){
        
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
